export const USER_DATA = 'USER_DATA';
export const USER_LOGIN = 'USER_LOGIN';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
export const MODAL_NAME = 'MODAL_NAME';
export const GLOBAL_INTERESTS = 'GLOBAL_INTERESTS';
export const USER_INTERESTS = 'USER_INTERESTS';
export const LOCATION_ACCESS = 'LOCATION_ACCESS';